### PR TITLE
Update createParamDecorator for NestJS v7

### LINKED ISSUE #16: @Loader decorator broken with new NestJS release (v7)
The method signature for "createParamDecorator" changed in the new release of NestJS. I believe it should now be:

`export const Loader = createParamDecorator((data: string, ctx: ExecutionContext) => {
  const context = GqlExecutionContext.create(ctx).getContext()
//rest of functionality using this context
});
`

### LINKED ISSUE #20: Error with NestJS 7
I have tried upgrading to NestJS 7.0.7 and nestjs-dataloader to 7.0.0 and I'm getting the following error when trying to start the server:

```
The types returned by 'clear(...)' are incompatible between these types.
        Type 'DataLoader<number, Topic, number>' is not assignable to type 'this'.

11   generateDataLoader(): DataLoader<number, Topic> {
```

This is how my code looks like:

```typescript
import DataLoader from 'dataloader';
import { Injectable } from '@nestjs/common';
import { NestDataLoader } from 'nestjs-dataloader';
import { TopicsService } from './topics.service';
import { Topic } from './topics.entity';

@Injectable()
export class TopicsLoader implements NestDataLoader<number, Topic> {
  constructor(private readonly topicsService: TopicsService) { }

  generateDataLoader(): DataLoader<number, Topic> {
    return new DataLoader<number, Topic>(keys => this.topicsService.findByIds([...keys]));
  }
}
```

### LINKED ISSUE #23: Error with Nest v7
Getting `undefined is not a function`
Here is stack trace. Any updates on this?
```
TypeError: undefined is not a function",
            "    at exports.Loader.common_1.createParamDecorator (/usr/src/app/node_modules/nestjs-dataloader/dist/index.js:55:48)",
            "    at shared_utils_1.isFunction.args (/usr/src/app/node_modules/@nestjs/core/helpers/context-utils.js:32:28)",
            "    at resolveParamValue (/usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:141:31)",
            "    at Array.map (<anonymous>)",
            "    at pipesFn 
```

### PR DESCRIPTION
**Pull request by pablo-abc**
This PR updates createParamDecorator to follow NestJS v7 changes to its signature.

Should fix #20, fix #16 and fix #23

### CODE REVIEW

**Comment by brianschardt** [comment]
can we get this merged in?

**Comment by parkerself22** [comment]
@krislefeber doesn't look like this made it into the `7.0.1` release, any timeline on getting this change published? We have a lot of classes that implement `NestDataLoader` that are all broken when I try to upgrade

**Comment by brianschardt** [comment]
it worked for me, if you are using docker you need to rebuild your image

**Comment by brianschardt** [comment]
it worked for me

**Comment by parkerself22** [comment]
@brianschardt not sure I understand, I'm just talking about the npm package. We have the latest published version installed (7.0.1), when I look at `node_modules/nestjs-dataloader/index.ts` it still has `import * as DataLoader from 'dataloader';` which is what causes the typescript error in #20.

**Comment by brianschardt** [comment]
it fixed my issue here : https://github.com/krislefeber/nestjs-dataloader/issues/23

**Comment by parkerself22** [comment]
@brianschardt strange, this PR definitely didn't make it into `7.0.1` published on npm. What's in your `package.json`?

**Comment by brianschardt** [comment]
"nestjs-dataloader": "^7.0.1"

**Comment by parkerself22** [comment]
@brianschardt ahh weird, your issue must have been fixed by a different change that did make it into the 7.0.1 publish. the fix for #20 did not:
image

**Comment by krislefeber** [comment]
@parkerself22, this was a fix in #15. What exactly would you expect it to be?

**Comment by parkerself22** [comment]
@krislefeber I'd expect it to be what was merged in this PR as a fix for #20: `import DataLoader from 'dataloader';`.

**Pull request merged**
